---
name: Deploying website with surge

on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploying_surge_job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Setup Surge
        run: npm-install --global surge
      - name: Execute deployment of surge
        run: ./ project001_lehamzash.surge.sh --token ${{ secrets.project001_surge_token}}

...

